require 'simplecov'
SimpleCov.start 'rails'
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'vcr'

VCR.configure do |c|
  c.cassette_library_dir='spec/cassettes'
  c.hook_into :webmock
end

RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # These two settings work together to allow you to limit a spec run
  # to individual examples or groups you care about by tagging them with
  # `:focus` metadata. When nothing is tagged with `:focus`, all examples
  # get run.
  config.filter_run :focus
  config.run_all_when_everything_filtered = true

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = 'doc'
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
def return_commits
[{"sha": "aaab5025cac67ebd092296a3fb34aad401ae2377",
    "commit": {
      "author": {
        "name": "Kami Boers",
        "email": "kamiboers@gmail.com",
        "date": "2016-05-26T17:43:56Z"
      },
      "committer": {
        "name": "Kami Boers",
        "email": "kamiboers@gmail.com",
        "date": "2016-05-26T17:43:56Z"
      },
      "message": "commits display",
      "tree": {
        "sha": "ad7e6859426693512001f170642da128c2528eca",
        "url": "https://api.github.com/repos/kamiboers/ihub/git/trees/ad7e6859426693512001f170642da128c2528eca"
      },
      "url": "https://api.github.com/repos/kamiboers/ihub/git/commits/aaab5025cac67ebd092296a3fb34aad401ae2377",
      "comment_count": 0
    },
    "url": "https://api.github.com/repos/kamiboers/ihub/commits/aaab5025cac67ebd092296a3fb34aad401ae2377",
    "html_url": "https://github.com/kamiboers/ihub/commit/aaab5025cac67ebd092296a3fb34aad401ae2377",
    "comments_url": "https://api.github.com/repos/kamiboers/ihub/commits/aaab5025cac67ebd092296a3fb34aad401ae2377/comments",
    "author": {
      "login": "kamiboers",
      "id": 15680831,
      "avatar_url": "https://avatars.githubusercontent.com/u/15680831?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kamiboers",
      "html_url": "https://github.com/kamiboers",
      "followers_url": "https://api.github.com/users/kamiboers/followers",
      "following_url": "https://api.github.com/users/kamiboers/following{/other_user}",
      "gists_url": "https://api.github.com/users/kamiboers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kamiboers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kamiboers/subscriptions",
      "organizations_url": "https://api.github.com/users/kamiboers/orgs",
      "repos_url": "https://api.github.com/users/kamiboers/repos",
      "events_url": "https://api.github.com/users/kamiboers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kamiboers/received_events",
      "type": "User",
      "site_admin": false
    },
    "committer": {
      "login": "kamiboers",
      "id": 15680831,
      "avatar_url": "https://avatars.githubusercontent.com/u/15680831?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kamiboers",
      "html_url": "https://github.com/kamiboers",
      "followers_url": "https://api.github.com/users/kamiboers/followers",
      "following_url": "https://api.github.com/users/kamiboers/following{/other_user}",
      "gists_url": "https://api.github.com/users/kamiboers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kamiboers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kamiboers/subscriptions",
      "organizations_url": "https://api.github.com/users/kamiboers/orgs",
      "repos_url": "https://api.github.com/users/kamiboers/repos",
      "events_url": "https://api.github.com/users/kamiboers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kamiboers/received_events",
      "type": "User",
      "site_admin": false
    },
    "parents": [
      {
        "sha": "c0faaed146666ec44d65b8facf61e381317ab94d",
        "url": "https://api.github.com/repos/kamiboers/ihub/commits/c0faaed146666ec44d65b8facf61e381317ab94d",
        "html_url": "https://github.com/kamiboers/ihub/commit/c0faaed146666ec44d65b8facf61e381317ab94d"
      }
    ]
  },
  {
    "sha": "c0faaed146666ec44d65b8facf61e381317ab94d",
    "commit": {
      "author": {
        "name": "Kami Boers",
        "email": "kamiboers@gmail.com",
        "date": "2016-05-26T15:10:01Z"
      },
      "committer": {
        "name": "Kami Boers",
        "email": "kamiboers@gmail.com",
        "date": "2016-05-26T15:10:01Z"
      },
      "message": "add repo display",
      "tree": {
        "sha": "80155ed848888b7eba5942b72ce766320035dd46",
        "url": "https://api.github.com/repos/kamiboers/ihub/git/trees/80155ed848888b7eba5942b72ce766320035dd46"
      },
      "url": "https://api.github.com/repos/kamiboers/ihub/git/commits/c0faaed146666ec44d65b8facf61e381317ab94d",
      "comment_count": 0
    },
    "url": "https://api.github.com/repos/kamiboers/ihub/commits/c0faaed146666ec44d65b8facf61e381317ab94d",
    "html_url": "https://github.com/kamiboers/ihub/commit/c0faaed146666ec44d65b8facf61e381317ab94d",
    "comments_url": "https://api.github.com/repos/kamiboers/ihub/commits/c0faaed146666ec44d65b8facf61e381317ab94d/comments",
    "author": {
      "login": "kamiboers",
      "id": 15680831,
      "avatar_url": "https://avatars.githubusercontent.com/u/15680831?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kamiboers",
      "html_url": "https://github.com/kamiboers",
      "followers_url": "https://api.github.com/users/kamiboers/followers",
      "following_url": "https://api.github.com/users/kamiboers/following{/other_user}",
      "gists_url": "https://api.github.com/users/kamiboers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kamiboers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kamiboers/subscriptions",
      "organizations_url": "https://api.github.com/users/kamiboers/orgs",
      "repos_url": "https://api.github.com/users/kamiboers/repos",
      "events_url": "https://api.github.com/users/kamiboers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kamiboers/received_events",
      "type": "User",
      "site_admin": false
    },
    "committer": {
      "login": "kamiboers",
      "id": 15680831,
      "avatar_url": "https://avatars.githubusercontent.com/u/15680831?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kamiboers",
      "html_url": "https://github.com/kamiboers",
      "followers_url": "https://api.github.com/users/kamiboers/followers",
      "following_url": "https://api.github.com/users/kamiboers/following{/other_user}",
      "gists_url": "https://api.github.com/users/kamiboers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kamiboers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kamiboers/subscriptions",
      "organizations_url": "https://api.github.com/users/kamiboers/orgs",
      "repos_url": "https://api.github.com/users/kamiboers/repos",
      "events_url": "https://api.github.com/users/kamiboers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kamiboers/received_events",
      "type": "User",
      "site_admin": false
    },
    "parents": [
      {
        "sha": "7bf2e3868d4cb71476048c85ecbdbeb87a3d0e0b",
        "url": "https://api.github.com/repos/kamiboers/ihub/commits/7bf2e3868d4cb71476048c85ecbdbeb87a3d0e0b",
        "html_url": "https://github.com/kamiboers/ihub/commit/7bf2e3868d4cb71476048c85ecbdbeb87a3d0e0b"
      }
    ]
  },
  {
    "sha": "7bf2e3868d4cb71476048c85ecbdbeb87a3d0e0b",
    "commit": {
      "author": {
        "name": "Kami Boers",
        "email": "kamiboers@gmail.com",
        "date": "2016-05-26T02:00:34Z"
      },
      "committer": {
        "name": "Kami Boers",
        "email": "kamiboers@gmail.com",
        "date": "2016-05-26T02:00:34Z"
      },
      "message": "initial commit",
      "tree": {
        "sha": "64604b6e8a0e657d964df5cb6a1031c1e6a17738",
        "url": "https://api.github.com/repos/kamiboers/ihub/git/trees/64604b6e8a0e657d964df5cb6a1031c1e6a17738"
      },
      "url": "https://api.github.com/repos/kamiboers/ihub/git/commits/7bf2e3868d4cb71476048c85ecbdbeb87a3d0e0b",
      "comment_count": 0
    },
    "url": "https://api.github.com/repos/kamiboers/ihub/commits/7bf2e3868d4cb71476048c85ecbdbeb87a3d0e0b",
    "html_url": "https://github.com/kamiboers/ihub/commit/7bf2e3868d4cb71476048c85ecbdbeb87a3d0e0b",
    "comments_url": "https://api.github.com/repos/kamiboers/ihub/commits/7bf2e3868d4cb71476048c85ecbdbeb87a3d0e0b/comments",
    "author": {
      "login": "kamiboers",
      "id": 15680831,
      "avatar_url": "https://avatars.githubusercontent.com/u/15680831?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kamiboers",
      "html_url": "https://github.com/kamiboers",
      "followers_url": "https://api.github.com/users/kamiboers/followers",
      "following_url": "https://api.github.com/users/kamiboers/following{/other_user}",
      "gists_url": "https://api.github.com/users/kamiboers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kamiboers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kamiboers/subscriptions",
      "organizations_url": "https://api.github.com/users/kamiboers/orgs",
      "repos_url": "https://api.github.com/users/kamiboers/repos",
      "events_url": "https://api.github.com/users/kamiboers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kamiboers/received_events",
      "type": "User",
      "site_admin": false
    },
    "committer": {
      "login": "kamiboers",
      "id": 15680831,
      "avatar_url": "https://avatars.githubusercontent.com/u/15680831?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kamiboers",
      "html_url": "https://github.com/kamiboers",
      "followers_url": "https://api.github.com/users/kamiboers/followers",
      "following_url": "https://api.github.com/users/kamiboers/following{/other_user}",
      "gists_url": "https://api.github.com/users/kamiboers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kamiboers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kamiboers/subscriptions",
      "organizations_url": "https://api.github.com/users/kamiboers/orgs",
      "repos_url": "https://api.github.com/users/kamiboers/repos",
      "events_url": "https://api.github.com/users/kamiboers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kamiboers/received_events",
      "type": "User",
      "site_admin": false
    },
    "parents": [

    ]
  }
]
end

end
